package fr.insalyon.pyp.tools;public class Constants {		public static final String TAG = "PYP-android";	public static final String PARAMNAME = "PYPParamName";	public static final int LOGIN_CONST = 2001;
	public static final int REGISTER_CONST = 2002;
	public static final int FORGOT_PASSWORD_CONST = 2003;
	public static final int RESET_PASSWORD_AFTER_RECOVERY_CONST = 2004;
	public static final int MAIN_CONST = 3001;
	public static final int PROFILE_CONST = 4001;
	public static final int SECURITY_CONST = 4002;
	public static final int PERSONAINFO_CONST = 4003;	public static final int INTRESTS_CONST = 4004;
	public static final int CREATE_EVENTS_CONST = 5001;	public static final int CREAT_LOCAL_PLACE_CONST = 5002;	public static final int GET_PLACES_CONST = 5003;	public static final int EVENT_INTREST_CONST = 5004;	public static final int MANAGE_PERSONAL_EVENTS_CONST = 5005;	public static final int GET_EVENT_DETAIL_CONST = 5005;	public static final int MENU_ITEM_1 = 100;	public static final int MENU_ITEM_2 = 200;			public static final int AREA_RADIUS = 5000;	public static final int BAR_RADIOUS = 500;	//popups id		public static final String WrongUsernameOrPassword = "WrongUsernameOrPassword";	public static final String IncompleatData = "IncompleatData";	public static final String InvalidEmail = "InvalidEmail";	public static final String EmailAlreadyUsed = "EmailAlreadyUsed";	public static final String UsernameAlreadyUsed = "UsernameAlreadyUsed";	public static final String passwordTooShort = "passwordTooShort";	public static final String passwordsDontMatch = "passwordsDontMatch";	public static final String usernameDoesNotExist = "usernameDoesNotExist";	public static final String curentPasswordWrong = "curentPasswordWrong";	public static final String dateFormatWrong = "dateFormatWrong";	public static final String timeFormatWrong = "timeFormatWrong";	public static final String WrongUsername = "wrongUsername";	public static final String NoSecretQuestion = "noSecretQuestion";	public static final String WrongAnswer = "WrongAnswer";	public static final String WrongData = "WrongData";	public static final String DifferentPassword = "DifferentPassword";	public static final String cantEditEvent = "cantEditEvent";	public static final String deleteQuestion = "deleteQuestion";	public static final String UpdatePersonalInfoOk = "updatePersonalInfoOk";	public static final String UpdateSecurityQuestionOk = "UpdateSecurityQuestionOk";	public static final String ThankGradeEvent = "ThankGradeEvent";}

